import type { CSSProperties } from "react";

/** Co-located styles for the agent editor's Skills tab (attach reusable skills). */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "baseline", gap: 12, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  hint: { fontSize: 13, color: "var(--text-muted)", marginBottom: 16, lineHeight: 1.45 } satisfies CSSProperties,
  search: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 10px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    marginBottom: 14,
  } satisfies CSSProperties,
  searchInput: {
    flex: 1,
    fontSize: 13,
    background: "transparent",
    border: "none",
    outline: "none",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (attached: boolean, dragging = false): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid " + (attached ? "var(--border-strong)" : "var(--border)"),
    background: attached ? "var(--bg-hover)" : "var(--bg-elevated)",
    opacity: dragging ? 0.4 : 1,
  }),
  handle: (attached: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    color: "var(--text-muted)",
    cursor: attached ? "grab" : "default",
    opacity: attached ? 1 : 0.25,
    flexShrink: 0,
    touchAction: "none",
  }),
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowName: { fontSize: 14, fontWeight: 600, display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  rowDesc: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginTop: 3,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  } satisfies CSSProperties,
  typeChip: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    padding: "1px 7px",
    borderRadius: 4,
  } satisfies CSSProperties,
  orderNo: { fontSize: 12, color: "var(--text-muted)", width: 18, textAlign: "right" } satisfies CSSProperties,
} as const;
